In [188]:
import pickle
import json
import requests
import pandas as pd
from riotwatcher import LolWatcher, ApiError
import numpy as np
import matplotlib.pyplot as plt
# from time import sleep

with open('data/api-key.txt', 'r') as api:
    API_KEY = api.read()
lol_watcher = LolWatcher(API_KEY)

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4)"+
                    " AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135"+
                    " Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
    "Accept-Charset": "application/x-www-form-urlencoded; charset=UTF-8",
    "Origin": "https://developer.riotgames.com",
    "X-Riot-Token": API_KEY
}

CHAMP_ID = 64
TESTMATCH = "4748107995"

np.random.seed(7)

In [189]:
import os
import datetime

#import IPython
#import IPython.display
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf

mpl.rcParams['figure.figsize'] = (8, 6)
mpl.rcParams['axes.grid'] = False

In [190]:
dfs_dict = pickle.load(open("data/timeline-di.p", "rb"))

In [191]:
gameids = list(dfs_dict.keys())
gameids.sort()
train_ids = gameids[0:int(len(gameids)*.8)]
val_ids = gameids[int(len(gameids)*.8):int(len(gameids)*.9)]
test_ids = gameids[int(len(gameids)*.9):]

In [192]:
dfs_dict[train_ids[1]][0:10]

timestamp  0currentGold  1currentGold  2currentGold  3currentGold  \
0        0.0         500.0         500.0         500.0         500.0   
1    60021.0           0.0           0.0           0.0           0.0   
2   120038.0         126.0         194.0          98.0          63.0   
3   180049.0         455.0         453.0         469.0         614.0   
4   240068.0         781.0         947.0         717.0        1358.0   
5   300080.0          87.0        1232.0         176.0        1830.0   
6   360102.0         418.0        1314.0         587.0         965.0   
7   420109.0          59.0         346.0         257.0         331.0   
8   480142.0         383.0         802.0         688.0         840.0   
9   540170.0         781.0        1284.0         961.0        1409.0   

   4currentGold  5currentGold  6currentGold  7currentGold  8currentGold  ...  \
0         500.0         500.0         500.0         500.0         500.0  ...   
1           0.0           0.0           0.0           0.0          15.0  ...   
2          44.0          42.0         121.0          98.0          98.0  ...   
3         134.0         311.0         138.0         381.0         171.0  ...   
4         339.0         560.0         261.0          79.0          46.0  ...   
5         558.0         144.0         526.0         495.0         297.0  ...   
6         793.0         728.0         821.0         859.0         533.0  ...   
7         192.0         492.0          48.0          49.0          83.0  ...   
8         430.0         921.0         482.0         429.0         344.0  ...   
9         707.0        1177.0         643.0          55.0         545.0  ...   

        1y       2y      3y      4y       6y       7y       8y       9y  \
0    361.0    293.0   471.0   649.0  14291.0  14223.0  14401.0  14579.0   
1   5918.0   7122.0  1061.0  5697.0   6837.0   6371.0   4256.0   5165.0   
2   2128.0   6876.0  2722.0  2688.0   7753.0   7563.0   3038.0   2617.0   
3   5054.0   6181.0  4045.0  3444.0   5250.0   7136.0   5056.0   7300.0   
4   5411.0   7268.0  2113.0  2290.0  13996.0   8934.0   8532.0   2420.0   
5   8268.0   6871.0  1171.0  1372.0   9862.0   7741.0   1260.0   1687.0   
6  13841.0  13390.0   520.0  1237.0   4689.0   5565.0   1573.0   1547.0   
7   3688.0   7655.0  2539.0  2698.0  13300.0  11346.0   2695.0   3577.0   
8   5488.0   5054.0  4249.0  5181.0  10001.0   7477.0   5826.0   5571.0   
9   7369.0   6941.0  4785.0  7242.0   7701.0   8166.0   7717.0   7742.0   

   player_x  player_y  
0   14486.0   14511.0  
1   13192.0   14166.0  
2    4234.0   13602.0  
3    3871.0   13475.0  
4    4153.0   13654.0  
5    4254.0   13656.0  
6    4405.0   14040.0  
7    3241.0   13286.0  
8    2137.0   11848.0  
9    4345.0   13525.0  

[10 rows x 61 columns]

In [193]:
#train_ids[0]
test0 = dfs_dict[train_ids[0]][0:20].drop(["timestamp"],axis=1)
test1 = dfs_dict[train_ids[1]][0:20].drop(["timestamp"],axis=1)
column_indices = {name: i for i, name in enumerate(test0.columns)}

In [194]:
test0

0currentGold  1currentGold  2currentGold  3currentGold  4currentGold  \
0          500.0         500.0         500.0         500.0         500.0   
1           25.0         420.0          25.0          25.0          25.0   
2          122.0         190.0         115.0         122.0          68.0   
3          356.0         634.0         486.0         521.0         276.0   
4          128.0        1475.0         128.0         750.0         485.0   
5          453.0         212.0         454.0          57.0          80.0   
6          803.0         630.0         751.0         439.0         214.0   
7         1316.0        1366.0          37.0          23.0         534.0   
8           89.0         231.0         361.0         323.0         119.0   
9          367.0         395.0        1114.0         968.0         607.0   
10         988.0         889.0         148.0        1380.0         836.0   
11         554.0         241.0         638.0         177.0          70.0   
12        1503.0         655.0         927.0         624.0         246.0   
13         535.0        1321.0         331.0         893.0         425.0   
14        1279.0         118.0         538.0        1742.0         195.0   
15         717.0         640.0         800.0         194.0         474.0   
16        1188.0        1057.0        1402.0         699.0         464.0   
17         502.0        1327.0          65.0          21.0         634.0   
18         625.0        1579.0         432.0         584.0         125.0   
19        1020.0        1803.0         140.0        1412.0          65.0   

    5currentGold  6currentGold  7currentGold  8currentGold  9currentGold  ...  \
0          500.0         500.0         500.0         500.0         500.0  ...   
1            0.0           0.0           0.0           0.0           0.0  ...   
2           41.0         144.0         125.0          83.0          22.0  ...   
3          359.0         540.0         380.0         373.0         198.0  ...   
4          816.0          99.0          89.0         648.0          94.0  ...   
5          264.0         413.0         379.0        1050.0         228.0  ...   
6          527.0         696.0         750.0         273.0         429.0  ...   
7          817.0         198.0          74.0         224.0          29.0  ...   
8          308.0         946.0        1129.0         674.0         238.0  ...   
9          557.0          75.0          57.0         954.0         195.0  ...   
10         905.0         648.0         329.0        1307.0         371.0  ...   
11         215.0         286.0         372.0         207.0         632.0  ...   
12         379.0         815.0         944.0         413.0         826.0  ...   
13         648.0        1585.0         296.0         881.0        1025.0  ...   
14         771.0        2098.0        1083.0        1359.0        1436.0  ...   
15        1517.0          35.0         652.0         815.0         207.0  ...   
16         204.0         510.0         931.0        1243.0         197.0  ...   
17         549.0        1509.0         639.0        1722.0         694.0  ...   
18        1109.0        2497.0         851.0          45.0         234.0  ...   
19          13.0        2805.0        1123.0         457.0         519.0  ...   

         1y       3y      4y       5y       6y       7y       8y       9y  \
0     361.0    471.0   649.0  14511.0  14291.0  14223.0  14401.0  14579.0   
1     542.0   1013.0   679.0  13885.0  11463.0   8416.0   7493.0  11457.0   
2    8042.0   2285.0  2107.0  12344.0  10103.0   7015.0   3101.0   2597.0   
3    5011.0   3118.0  3266.0  13855.0   4991.0   7337.0   3991.0   4151.0   
4    3263.0   2921.0  2816.0  10840.0   9761.0   9040.0   3937.0  11836.0   
5    7169.0   1556.0  1712.0  12890.0   8567.0   8337.0   3373.0   3711.0   
6   12602.0   1340.0  4032.0  13411.0   4964.0   7590.0   2309.0   5108.0   
7    5325.0    554.0  5437.0  12869.0  11326.0   8390.0   4371.0  12836.0   
8   10843.0 

In [195]:
class WindowGenerator():
    def __init__(self, input_width, label_width, shift,
                 full_df=test0, val_df = test1,
                 dfdi=dfs_dict,
                 #train_df=train_df, val_df=val_df, test_df=test_df,
                 label_columns=None):
        # Store the raw data.
        #self.train_df = train_df
        #self.val_df = val_df
        #self.test_df = test_df
        self.full_df = full_df
        self.val_df = val_df
        self.dfdi = dfdi
        self.trainli = None
        self.valli = None
        self.testli = None

        # Work out the label column indices.
        self.label_columns = label_columns
        if label_columns is not None:
            self.label_columns_indices = {name: i for i, name in
                                                                        enumerate(label_columns)}
        self.column_indices = {name: i for i, name in
                                                     enumerate(full_df.columns)}

        # Work out the window parameters.
        self.input_width = input_width
        self.label_width = label_width
        self.shift = shift

        self.total_window_size = input_width + shift

        self.input_slice = slice(0, input_width)
        self.input_indices = np.arange(self.total_window_size)[self.input_slice]

        self.label_start = self.total_window_size - self.label_width
        self.labels_slice = slice(self.label_start, None)
        self.label_indices = np.arange(self.total_window_size)[self.labels_slice]

    def __repr__(self):
        return '\n'.join([
                f'Total window size: {self.total_window_size}',
                f'Input indices: {self.input_indices}',
                f'Label indices: {self.label_indices}',
                f'Label column name(s): {self.label_columns}'])

In [196]:
def split_window(self, features):
    inputs = features[:, self.input_slice, :]
    labels = features[:, self.labels_slice, :]
    if self.label_columns is not None:
        labels = tf.stack(
                [labels[:, :, self.column_indices[name]] for name in self.label_columns],
                axis=-1)
    

    # Slicing doesn't preserve static shape information, so set the shapes
    # manually. This way the `tf.data.Datasets` are easier to inspect.
    inputs.set_shape([None, self.input_width, None])
    labels.set_shape([None, self.label_width, None])

    return inputs, labels

WindowGenerator.split_window = split_window

In [197]:
def plot(self, model=None, plot_col="player_x", max_subplots=3):
    inputs, labels = self.example
    plt.figure(figsize=(12, 8))
    plot_col_index = self.column_indices[plot_col]
    print(plot_col_index, type(plot_col_index))
    max_n = min(max_subplots, len(inputs))
    for n in range(max_n):
        plt.subplot(3, 1, n+1)
        plt.ylabel(f'{plot_col} [normed]')
        plt.plot(self.input_indices, inputs[n, :, plot_col_index],
                         label='Inputs', marker='.', zorder=-10)

        if self.label_columns:
            print(type(self.label_columns_indices))
            label_col_index = self.label_columns_indices.get(plot_col, None)
            print(label_col_index)
        else:
            label_col_index = plot_col_index

        if label_col_index is None:
            continue

        print(self.label_indices)
        plt.scatter(self.label_indices, labels[n, :, label_col_index],
                                edgecolors='k', label='Labels', c='#2ca02c', s=64)
        if model is not None:
            predictions = model(inputs)
            plt.scatter(self.label_indices, predictions[n, :, label_col_index],
                                    marker='X', edgecolors='k', label='Predictions',
                                    c='#ff7f0e', s=64)

        if n == 0:
            plt.legend()

    plt.xlabel('Time [h]')

WindowGenerator.plot = plot

In [198]:
def make_dataset(self, data, list_me=False):
    data = np.array(data, dtype=np.float32)
    ds = tf.keras.preprocessing.timeseries_dataset_from_array(
            data=data,
            targets=None,
            sequence_length=self.total_window_size,
            sequence_stride=1,
            shuffle=True,
            batch_size=32,)

    ds = ds.map(self.split_window)
    if list_me:
        return list(ds)
    return ds

WindowGenerator.make_dataset = make_dataset

In [199]:
def make_split_from_dfdi(self,splits=(.8,.9),minmax=(0,20)):
    # minmax is start and end time of window being sampled from.
    # splits is where the data is being split for train val test split
    if self.dfdi is None:
        print("no dfdi attached")
        raise KeyError("no dfdi attached")
    gameids = list(self.dfdi.keys())
    gameids.sort()
    train_ids = gameids[0:int(len(gameids)*splits[0])]
    val_ids = gameids[int(len(gameids)*splits[0]):int(len(gameids)*splits[1])]
    test_ids = gameids[int(len(gameids)*splits[1]):]
    if self.trainli is None:
        trainli = build_batch(self, self.dfdi, train_ids, minmax)
        train_feats = tf.concat([batch[0] for batch in trainli], axis=0)
        train_labels = tf.concat([batch[1] for batch in trainli], axis=0)
        
    if self.valli is None:
        valli = build_batch(self, self.dfdi, val_ids, minmax)
        val_feats = tf.concat([batch[0] for batch in valli], axis=0)
        val_labels = tf.concat([batch[1] for batch in valli], axis=0)
            
    if self.testli is None:
        testli = build_batch(self, self.dfdi, test_ids, minmax)
        test_feats = tf.concat([batch[0] for batch in testli], axis=0)
        test_labels = tf.concat([batch[1] for batch in testli], axis=0)
            
        
    print(train_feats.shape, train_labels.shape)
    self.train = (train_feats, train_labels)
    self.val = (val_feats, val_labels)
    self.test = (test_feats, test_labels)

WindowGenerator.make_split_from_dfdi = make_split_from_dfdi

In [200]:
@property
def example(self):
    """Get and cache an example batch of `inputs, labels` for plotting."""
    result = getattr(self, '_example', None)
    if result is None:
        # No example batch was found, so get one from the `.train` dataset
        result = next(iter(self.train))
        # And cache it for next time
        self._example = result
    return result

WindowGenerator.example = example

In [201]:
def build_batch(self, dfdi, id_li, minmax):
    dataset_li = []
    for match_id in id_li:
        df = dfdi[match_id]
        df = df.drop(["timestamp"], axis=1)
        df = df.iloc[minmax[0]:minmax[1]]
        dataset_li = dataset_li + make_dataset(self, data=df, list_me=True)
    return dataset_li

WindowGenerator.build_batch = build_batch

In [202]:
test0.columns

Index(['0currentGold', '1currentGold', '2currentGold', '3currentGold',
       '4currentGold', '5currentGold', '6currentGold', '7currentGold',
       '8currentGold', '9currentGold', '0totalGold', '1totalGold',
       '2totalGold', '3totalGold', '4totalGold', '5totalGold', '6totalGold',
       '7totalGold', '8totalGold', '9totalGold', '0level', '1level', '2level',
       '3level', '4level', '5level', '6level', '7level', '8level', '9level',
       '0jungleMinionsKilled', '1jungleMinionsKilled', '2jungleMinionsKilled',
       '3jungleMinionsKilled', '4jungleMinionsKilled', '5jungleMinionsKilled',
       '6jungleMinionsKilled', '7jungleMinionsKilled', '8jungleMinionsKilled',
       '9jungleMinionsKilled', '0x', '1x', '3x', '4x', '5x', '6x', '7x', '8x',
       '9x', '0y', '1y', '3y', '4y', '5y', '6y', '7y', '8y', '9y', 'player_x',
       'player_y'],
      dtype='object')

In [203]:
w2 = WindowGenerator(input_width=5, label_width=2, shift=2,
                     label_columns=["player_x","player_y"])
w2

Total window size: 7
Input indices: [0 1 2 3 4]
Label indices: [5 6]
Label column name(s): ['player_x', 'player_y']

In [205]:
single_step_window = WindowGenerator(
    input_width=1, label_width=1, shift=1,
    label_columns=["player_x", "player_y"])#,
single_step_window

Total window size: 2
Input indices: [0]
Label indices: [1]
Label column name(s): ['player_x', 'player_y']

In [208]:
single_step_window.make_split_from_dfdi()

(1824, 1, 60) (1824, 1, 2)


In [293]:
def tensor_distance_mae(y_true, y_pred):
    """takes tuple of 2 tensors and returns the sum distance between the points"""
    dx2 = (y_true[:,:,0] - y_pred[:,:,0])**2
    dy2 = (y_true[:,:,1] - y_pred[:,:,1])**2
    dist = (dx2 + dy2)**.5
    dist_sum = tf.math.reduce_mean(dist)
    return dist_sum

In [294]:
def tensor_distance_rmse(y_true, y_pred):
    """takes tuple of 2 tensors and returns the sum distance between the points"""
    dx2 = (y_true[:,:,0] - y_pred[:,:,0])**2
    dy2 = (y_true[:,:,1] - y_pred[:,:,1])**2
    dist2 = dx2 + dy2
    dist2_sum = tf.math.reduce_mean(dist2)
    rmse = dist2_sum**.5
    return rmse

In [295]:
"""def tensor_distance_rmse_pure(y_true, y_pred):
    dx2 = (y_true[:,:,0] - y_pred[:,:,0])**2
    dy2 = (y_true[:,:,1] - y_pred[:,:,1])**2
    dist2 = dx2 + dy2
    dist2_sum = tf.math.reduce_sum(dist2)
    rmse = dist2_sum**.5
    return tf.pow(tf.math.reduce_sum(tf.pow(y_true[:,:,0] - y_pred[:,:,0], 2)
                                     + dy2),.5)"""

'def tensor_distance_rmse_pure(y_true, y_pred):\n    dx2 = (y_true[:,:,0] - y_pred[:,:,0])**2\n    dy2 = (y_true[:,:,1] - y_pred[:,:,1])**2\n    dist2 = dx2 + dy2\n    dist2_sum = tf.math.reduce_sum(dist2)\n    rmse = dist2_sum**.5\n    return tf.pow(tf.math.reduce_sum(tf.pow(y_true[:,:,0] - y_pred[:,:,0], 2)\n                                     + dy2),.5)'

In [297]:
class Baseline(tf.keras.Model):
    def __init__(self, label_index=None):
        super().__init__()
        self.label_index = label_index

    def call(self, inputs):
        if self.label_index is None:
            return inputs
        elif isinstance(self.label_index,(list,tuple)):
            return inputs[:,:, self.label_index[0]:self.label_index[1]+1]
        result = inputs[:, :, self.label_index]
        return result[:, :, tf.newaxis]

In [298]:
linear = tf.keras.Sequential([
    tf.keras.layers.Dense(units=2)
])

In [299]:
dense = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=2)
])

In [300]:
train_hold = single_step_window.train# = tf.data.Dataset.from_tensor_slices([train_feats, train_labels])
val_hold = single_step_window.train
test_hold = single_step_window.test

In [301]:
train_hold[1]#[-1]

<tf.Tensor: shape=(1824, 1, 2), dtype=float32, numpy=
array([[[ 9254.,  7471.]],

       [[ 6598.,  6970.]],

       [[ 8023.,  7885.]],

       ...,

       [[ 7577.,  7104.]],

       [[ 8755.,  3754.]],

       [[12450.,  2352.]]], dtype=float32)>

In [324]:
baseline = Baseline(label_index=[column_indices["player_x"],column_indices["player_y"]])#[column_indices["player_x"],column_indices["player_y"]])
baseline.compile(loss=tensor_distance_mae,
                 metrics=tensor_distance_mae)

In [325]:
linear.compile(loss=tensor_distance_mae,
               metrics=tensor_distance_mae,
               optimizer=tf.optimizers.Adam()
              )

In [326]:
dense.compile(loss=tensor_distance_mae,
               metrics=tensor_distance_mae,
               optimizer=tf.optimizers.Adam()
              )

In [327]:
baseline.fit(x=train_hold[0],
           y=train_hold[1],
           batch_size=32,
           epochs=30,
           verbose=1,
           validation_data=val_hold
          )

Epoch 1/30
57/57 [==============================] - 0s 5ms/step - loss: 4719.3911 - tensor_distance_mae: 4719.3911 - val_loss: 4719.3911 - val_tensor_distance_mae: 4719.3911
Epoch 2/30
57/57 [==============================] - 0s 2ms/step - loss: 4719.3901 - tensor_distance_mae: 4719.3901 - val_loss: 4719.3911 - val_tensor_distance_mae: 4719.3911
Epoch 3/30
57/57 [==============================] - 0s 1ms/step - loss: 4719.3896 - tensor_distance_mae: 4719.3896 - val_loss: 4719.3911 - val_tensor_distance_mae: 4719.3911
Epoch 4/30
57/57 [==============================] - 0s 2ms/step - loss: 4719.3911 - tensor_distance_mae: 4719.3911 - val_loss: 4719.3911 - val_tensor_distance_mae: 4719.3911
Epoch 5/30
57/57 [==============================] - 0s 3ms/step - loss: 4719.3916 - tensor_distance_mae: 4719.3916 - val_loss: 4719.3911 - val_tensor_distance_mae: 4719.3911
Epoch 6/30
57/57 [==============================] - 0s 4ms/step - loss: 4719.3911 - tensor_distance_mae: 4719.3911 - val_loss: 471

In [328]:
linear.fit(x=train_hold[0],
           y=train_hold[1],
           batch_size=32,
           epochs=30,
           verbose=1,
           validation_data=val_hold
          )

Epoch 1/30
57/57 [==============================] - 0s 4ms/step - loss: 3835.2539 - tensor_distance_mae: 3835.2539 - val_loss: 3801.8513 - val_tensor_distance_mae: 3801.8513
Epoch 2/30
57/57 [==============================] - 0s 2ms/step - loss: 3805.3037 - tensor_distance_mae: 3805.3037 - val_loss: 3791.2224 - val_tensor_distance_mae: 3791.2224
Epoch 3/30
57/57 [==============================] - 0s 2ms/step - loss: 3799.9502 - tensor_distance_mae: 3799.9502 - val_loss: 3784.4036 - val_tensor_distance_mae: 3784.4036
Epoch 4/30
57/57 [==============================] - 0s 2ms/step - loss: 3792.7280 - tensor_distance_mae: 3792.7280 - val_loss: 3772.1521 - val_tensor_distance_mae: 3772.1521
Epoch 5/30
57/57 [==============================] - 0s 2ms/step - loss: 3776.5063 - tensor_distance_mae: 3776.5063 - val_loss: 3760.7429 - val_tensor_distance_mae: 3760.7429
Epoch 6/30
57/57 [==============================] - 0s 2ms/step - loss: 3768.9814 - tensor_distance_mae: 3768.9814 - val_loss: 376

In [329]:
dense.fit(x=train_hold[0],
           y=train_hold[1],
           batch_size=32,
           epochs=30,
           verbose=1,
           validation_data=val_hold
          )

Epoch 1/30
57/57 [==============================] - 0s 4ms/step - loss: 3395.8005 - tensor_distance_mae: 3395.8005 - val_loss: 3272.8000 - val_tensor_distance_mae: 3272.8000
Epoch 2/30
57/57 [==============================] - 0s 2ms/step - loss: 3314.6870 - tensor_distance_mae: 3314.6870 - val_loss: 3271.4524 - val_tensor_distance_mae: 3271.4524
Epoch 3/30
57/57 [==============================] - 0s 2ms/step - loss: 3317.9678 - tensor_distance_mae: 3317.9678 - val_loss: 3275.7751 - val_tensor_distance_mae: 3275.7751
Epoch 4/30
57/57 [==============================] - 0s 2ms/step - loss: 3327.2930 - tensor_distance_mae: 3327.2930 - val_loss: 3251.8977 - val_tensor_distance_mae: 3251.8977
Epoch 5/30
57/57 [==============================] - 0s 2ms/step - loss: 3290.1982 - tensor_distance_mae: 3290.1982 - val_loss: 3206.0386 - val_tensor_distance_mae: 3206.0386
Epoch 6/30
57/57 [==============================] - 0s 2ms/step - loss: 3299.4260 - tensor_distance_mae: 3299.4260 - val_loss: 320

In [330]:
CONV_WIDTH = 3
conv_window = WindowGenerator(
    input_width=CONV_WIDTH,
    label_width=1,
    shift=1,
    label_columns=["player_x","player_y"])

conv_window

Total window size: 4
Input indices: [0 1 2]
Label indices: [3]
Label column name(s): ['player_x', 'player_y']

In [331]:
multi_step_dense = tf.keras.Sequential([
    # Shape: (time, features) => (time*features)
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=32, activation='relu'),
    tf.keras.layers.Dense(units=2),
    # Add back the time dimension.
    # Shape: (outputs) => (1, outputs)
    tf.keras.layers.Reshape([1, -1]),
])

multi_step_dense.compile(loss=tensor_distance_mae,
               metrics=tensor_distance_mae,
               optimizer=tf.optimizers.Adam()
              )

multi_step_dense.fit(x=train_hold[0],
           y=train_hold[1],
           batch_size=32,
           epochs=30,
           verbose=1,
           validation_data=val_hold
          )

Epoch 1/30
57/57 [==============================] - 0s 7ms/step - loss: 5780.5728 - tensor_distance_mae: 5780.5728 - val_loss: 4549.3442 - val_tensor_distance_mae: 4549.3442
Epoch 2/30
57/57 [==============================] - 0s 3ms/step - loss: 4435.4526 - tensor_distance_mae: 4435.4526 - val_loss: 4252.7021 - val_tensor_distance_mae: 4252.7021
Epoch 3/30
57/57 [==============================] - 0s 3ms/step - loss: 4139.9985 - tensor_distance_mae: 4139.9985 - val_loss: 3970.9265 - val_tensor_distance_mae: 3970.9265
Epoch 4/30
57/57 [==============================] - 0s 3ms/step - loss: 3936.2051 - tensor_distance_mae: 3936.2051 - val_loss: 3835.2871 - val_tensor_distance_mae: 3835.2871
Epoch 5/30
57/57 [==============================] - 0s 3ms/step - loss: 3837.0645 - tensor_distance_mae: 3837.0645 - val_loss: 3770.2722 - val_tensor_distance_mae: 3770.2722
Epoch 6/30
57/57 [==============================] - 0s 3ms/step - loss: 3815.5283 - tensor_distance_mae: 3815.5283 - val_loss: 377

In [332]:
linear_test_pred = linear.predict(x=test_hold[0])
baseline_test_pred = baseline.predict(x=test_hold[0])
dense_test_pred = dense.predict(x=test_hold[0])
mdense_test_pred = multi_step_dense.predict(x=test_hold[0])

In [333]:
linear_error = linear.evaluate(test_hold[0], test_hold[1])#, batch_size=128)
baseline_error = baseline.evaluate(test_hold[0], test_hold[1])
dense_error = dense.evaluate(test_hold[0], test_hold[1])
mdense_error = multi_step_dense.evaluate(test_hold[0], test_hold[1])
print("baseline rmse error:", baseline_error[1])
print("linear rmse error:", linear_error[1])
print("dense rmse error:", dense_error[1])
print("multistep dense rmse error:", mdense_error[1])

8/8 [==============================] - 0s 4ms/step - loss: 3470.7424 - tensor_distance_mae: 3686.0684
baseline rmse error: 4832.8427734375
linear rmse error: 3824.1611328125
dense rmse error: 3810.76904296875
multistep dense rmse error: 3686.068359375


In [334]:
test_hold[0]

<tf.Tensor: shape=(228, 1, 60), dtype=float32, numpy=
array([[[  690.,  1103.,   606., ...,  4542., 13523.,  2841.]],

       [[   60.,   762.,  1330., ...,  3861., 13448.,  3137.]],

       [[  221.,   909.,    37., ...,  5576., 13473.,  6629.]],

       ...,

       [[  642.,   620.,  1130., ...,  3475.,  3153., 13180.]],

       [[   89.,   553.,   238., ...,  8958.,  7904.,  8704.]],

       [[ 2451.,   354.,   508., ...,  2165.,  2620., 12212.]]],
      dtype=float32)>

In [335]:
mdense_test_pred

array([[[12629.87   ,  2373.7356 ]],

       [[11622.855  ,  2728.806  ]],

       [[ 9562.127  ,  6655.463  ]],

       [[ 9561.84   ,  2789.0862 ]],

       [[10580.419  ,  3505.526  ]],

       [[11383.817  ,  5823.6533 ]],

       [[12448.344  ,  3502.595  ]],

       [[ 6608.931  ,  5981.35   ]],

       [[12977.769  ,  2662.3792 ]],

       [[ 5722.3843 ,  6734.2734 ]],

       [[ 9045.053  ,  9105.584  ]],

       [[ 9480.969  ,  3621.3367 ]],

       [[ 9730.519  ,  4111.949  ]],

       [[12356.031  ,  2817.9192 ]],

       [[ 8755.961  ,  4239.32   ]],

       [[ 7122.2886 ,  6849.638  ]],

       [[ 6752.2603 ,  6839.568  ]],

       [[10001.53   ,  5760.845  ]],

       [[ 8361.504  ,  6754.1284 ]],

       [[10867.919  ,  7056.5337 ]],

       [[10596.565  ,  6522.2705 ]],

       [[ 8879.457  ,  7958.6978 ]],

       [[ 6828.2593 , 10138.21   ]],

       [[ 6692.8135 ,  6070.4556 ]],

       [[ 6786.128  ,  8155.2485 ]],

       [[10739.292  ,  6475.184  ]],

       [[ 94

In [336]:
test_hold[0][:,:,-2:]

<tf.Tensor: shape=(228, 1, 2), dtype=float32, numpy=
array([[[13523.,  2841.]],

       [[13448.,  3137.]],

       [[13473.,  6629.]],

       [[ 8419.,  1324.]],

       [[11051.,  4654.]],

       [[11434.,  5891.]],

       [[12366.,  2146.]],

       [[ 7555.,  6669.]],

       [[13418.,  2734.]],

       [[ 6256.,  6279.]],

       [[ 8269.,  6972.]],

       [[10773.,  5261.]],

       [[ 9070.,  3554.]],

       [[13003.,  2724.]],

       [[10349.,  3280.]],

       [[ 7250.,  4710.]],

       [[  311.,   649.]],

       [[12295.,  2626.]],

       [[ 7756.,  2449.]],

       [[11981.,  6662.]],

       [[10445.,  4762.]],

       [[14486., 14291.]],

       [[ 7023., 11402.]],

       [[ 3132.,  7574.]],

       [[ 3688.,  9894.]],

       [[12718.,  6216.]],

       [[11047.,  5058.]],

       [[ 3775., 11105.]],

       [[ 7417.,  9750.]],

       [[13827., 13452.]],

       [[11854.,  3146.]],

       [[14258., 14400.]],

       [[ 9847.,  4249.]],

       [[ 4881.,  8281.

In [337]:
test_hold[1]

<tf.Tensor: shape=(228, 1, 2), dtype=float32, numpy=
array([[[13003.,  2724.]],

       [[ 8419.,  1324.]],

       [[ 7555.,  6669.]],

       [[10773.,  5261.]],

       [[13418.,  2734.]],

       [[13523.,  2841.]],

       [[ 9070.,  3554.]],

       [[ 7250.,  4710.]],

       [[11434.,  5891.]],

       [[ 7756.,  2449.]],

       [[ 6256.,  6279.]],

       [[10349.,  3280.]],

       [[13448.,  3137.]],

       [[12366.,  2146.]],

       [[12295.,  2626.]],

       [[ 8269.,  6972.]],

       [[11051.,  4654.]],

       [[13473.,  6629.]],

       [[ 2706., 12710.]],

       [[ 4779.,  7333.]],

       [[ 7023., 11402.]],

       [[11047.,  5058.]],

       [[13827., 13452.]],

       [[ 9847.,  4249.]],

       [[ 3775., 11105.]],

       [[10445.,  4762.]],

       [[ 4881.,  8281.]],

       [[ 9344.,  7024.]],

       [[ 3688.,  9894.]],

       [[11854.,  3146.]],

       [[ 6589., 12618.]],

       [[11981.,  6662.]],

       [[ 7417.,  9750.]],

       [[14258., 14400.